workflows:
  android-workflow:
    name: Android Build
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        
    scripts:
      - name: Build Android APK
        script: |
          flutter packages pub get
          flutter build apk --release
          
    artifacts:
      - build/app/outputs/flutter-apk/*.apk